= ICMP Echo
:docinfo:
[preface]

The ICMP echo application is a example of packet processing built on Twister API which responds for the ICMP(Ping) packets.

== Overview
The ICMP echo application, on receiveing the icmp packets on the ports determined the  forwarding for each packet that is received on the ports. All the other fields in the packets remain the same - only the MAC addresses are affected as follows:

* The type field in ICMP packet is changed to make the packet as reply of an ICMP packet
* The checksum of the ICMP header is calculated
* The source IP address is replaced by the TX_PORT IP address
* The destination IP address is replaced by the source IP address of Querier
* The checksum of the Layer is calculated
* The source MAC address is replaced by the TX_PORT MAC address
* The destination MAC address is replaced by the Source MAC address of the received packet

== Compiling and Running the Application
Build the application using the following command:
--------------------------------------
make
--------------------------------------
To run the application in linuxapp environment
--------------------------------------
./ICMP_REPLY
--------------------------------------
