#!/bin/sh
sudo modprobe uio
a=`lsmod | grep igb_uio | wc -l`
if [ "$a" -eq "2" ]
then
    echo "Module already inserted"
else
    echo "Inserting Modules in kernel"
    sudo insmod ./dpdk/x86_64-native-linuxapp-gcc/kmod/igb_uio.ko
fi
python /home/twister/config/tw_config.py

