= ICMP Echo Application
:docinfo:
[preface]

ICMP application
This application sends the ICMP packets (ping), it takes ip from console, and sends the ICMP packets to this machine. When it gets the ICMP reply packet, it displays the ICMP parameters to user, like TTL, RTT, sequence number etc.

== Overview
ICMP Echo application construct the ICMP Echo packet by putting icmp_echo header on top of ipv4 header. This
* The source MAC address is replaced by the TX_PORT MAC address
* Destination MAC, if not known, is acquired by ARP.
* An ICMP packet is constructed with sequence number starting from 1 and incremented each time.
* On receiving ICMP reply, RTT is calculated and displayed on console.

== Compiling and Running the Application
Build the application using the following command:
--------------------------------------
make
--------------------------------------
To run the application in linuxapp environment
--------------------------------------
./ICMP_ECHO
--------------------------------------

