= ARP application
:docinfo:
[preface]

This application implements the address resolution protocol, it takes input as ipv4 address and finds the mac address of that machine if it exist on same network.

== Overview
This arp application construct the arp packet with broadcast mac and flood it into the same network. The machine whose MAC is required finds the pakcet and reply to sender. The sender extract the MAC and displays it to user. if machine does not reply within 5 seconds, ARP application assumes that machine does not exist.
. At any point user can type <exit> to exit from application.

* The source MAC address is replaced by the TX_PORT MAC address.
* Source IP is used from console input by user(ipv4).
* Destination MAC is written broadcast ff:ff:ff:ff:ff:ff
* The destined machine finds the packet and reply with its own mac address.
* The returned MAC address is shown on console.

== Compiling and Running the Application
Build the application using the following command:
--------------------------------------
make
--------------------------------------
To run the application in linuxapp environment
--------------------------------------
./ARP
--------------------------------------
