= Reverse ARP application
:docinfo:
[preface]

This application implements the reverse address resolution protocol(), it broadcasts its MAC address and RARP server replies to it and finds the mac address of that machine if it exist on same network.

== Overview
This application implements the reverse RARP protocol.
. At any point user can type <exit> to exit from application.

* The source MAC address is replaced by the TX_PORT MAC address.
* Source IP is not defined i.e, zero
* Destination IP is not defined i.e. zero
* Destination MAC is written broadcast ff:ff:ff:ff:ff:ff
* The RARP server running in the network finds the packet and reply the sender with its ip.
* The returned ip with mac is shown on console.

== Compiling and Running the Application
Build the application using the following command:
--------------------------------------
make
--------------------------------------
To run the application in linuxapp environment
--------------------------------------
./RARP
--------------------------------------
